"""initial schema

Revision ID: a8134230c660
Revises: 
Create Date: 2026-08-20 03:25:08.737024

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8134230c660'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('contract_symbol', sa.String(), nullable=False),
    sa.Column('timestamp_open', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_close', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bars_contract_symbol'), 'bars', ['contract_symbol'], unique=False)
    op.create_index(op.f('ix_bars_instrument'), 'bars', ['instrument'], unique=False)
    op.create_index('ux_bars_instrument_contract_open', 'bars', ['instrument', 'contract_symbol', 'timestamp_open'], unique=True)
    op.create_table('contract_specs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('root_symbol', sa.String(), nullable=False),
    sa.Column('contract_month', sa.Integer(), nullable=False),
    sa.Column('contract_year', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('contract_symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_specs_contract_symbol'), 'contract_specs', ['contract_symbol'], unique=True)
    op.create_index('ix_contract_specs_root_month_year', 'contract_specs', ['root_symbol', 'contract_month', 'contract_year'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('trade_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_version', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_correlation_id'), 'events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_trade_id'), 'events', ['trade_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('training_period_start', sa.Date(), nullable=False),
    sa.Column('training_period_end', sa.Date(), nullable=False),
    sa.Column('validation_period_start', sa.Date(), nullable=False),
    sa.Column('validation_period_end', sa.Date(), nullable=False),
    sa.Column('test_period_start', sa.Date(), nullable=False),
    sa.Column('test_period_end', sa.Date(), nullable=False),
    sa.Column('feature_set', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    op.create_index('ux_model_versions_model_version', 'model_versions', ['model_id', 'version'], unique=True)
    op.create_table('session_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('regular_session_start', sa.String(), nullable=False),
    sa.Column('regular_session_end', sa.String(), nullable=False),
    sa.Column('extended_session_start', sa.String(), nullable=True),
    sa.Column('extended_session_end', sa.String(), nullable=True),
    sa.Column('trading_start', sa.String(), nullable=False),
    sa.Column('trading_end', sa.String(), nullable=False),
    sa.Column('opening_range_minutes', sa.Integer(), nullable=False),
    sa.Column('no_new_entry_cutoff', sa.String(), nullable=False),
    sa.Column('flatten_cutoff', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('long_score', sa.Float(), nullable=False),
    sa.Column('long_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('short_score', sa.Float(), nullable=False),
    sa.Column('short_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regime', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_as_of'), 'signals', ['as_of'], unique=False)
    op.create_index(op.f('ix_signals_instrument'), 'signals', ['instrument'], unique=False)
    op.create_table('contract_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('root_symbol', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mapped_contract_id', sa.UUID(), nullable=False),
    sa.Column('previous_contract_id', sa.UUID(), nullable=True),
    sa.Column('is_roll_event', sa.Boolean(), nullable=False),
    sa.Column('price_adjustment', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['mapped_contract_id'], ['contract_specs.id'], ),
    sa.ForeignKeyConstraint(['previous_contract_id'], ['contract_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_mappings_root_symbol'), 'contract_mappings', ['root_symbol'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('entry', sa.Numeric(), nullable=False),
    sa.Column('target', sa.Numeric(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('probability_availability', sa.String(), nullable=False),
    sa.Column('probability_value', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('expected_mfe', sa.Numeric(), nullable=True),
    sa.Column('expected_mae', sa.Numeric(), nullable=True),
    sa.Column('blocking_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_instrument'), 'opportunities', ['instrument'], unique=False)
    op.create_index(op.f('ix_opportunities_signal_id'), 'opportunities', ['signal_id'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('approved_quantity', sa.Integer(), nullable=False),
    sa.Column('maximum_loss', sa.Numeric(), nullable=True),
    sa.Column('stop_distance', sa.Numeric(), nullable=True),
    sa.Column('risk_percentage', sa.Float(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_decisions_opportunity_id'), 'risk_decisions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_risk_decisions_outcome'), 'risk_decisions', ['outcome'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_decision_id', sa.UUID(), nullable=False),
    sa.Column('contract_symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('average_fill_price', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['risk_decision_id'], ['risk_decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_contract_symbol'), 'orders', ['contract_symbol'], unique=False)
    op.create_index(op.f('ix_orders_risk_decision_id'), 'orders', ['risk_decision_id'], unique=False)
    op.create_index(op.f('ix_orders_state'), 'orders', ['state'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('contract_symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('stop_price', sa.Numeric(), nullable=False),
    sa.Column('target_price', sa.Numeric(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_price', sa.Numeric(), nullable=True),
    sa.Column('close_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_contract_symbol'), 'positions', ['contract_symbol'], unique=False)
    op.create_index(op.f('ix_positions_order_id'), 'positions', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_order_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_contract_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_state'), table_name='orders')
    op.drop_index(op.f('ix_orders_risk_decision_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_contract_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_risk_decisions_outcome'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_opportunity_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_opportunities_signal_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_instrument'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_contract_mappings_root_symbol'), table_name='contract_mappings')
    op.drop_table('contract_mappings')
    op.drop_index(op.f('ix_signals_instrument'), table_name='signals')
    op.drop_index(op.f('ix_signals_as_of'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('session_configs')
    op.drop_index('ux_model_versions_model_version', table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_events_trade_id'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_correlation_id'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_contract_specs_root_month_year', table_name='contract_specs')
    op.drop_index(op.f('ix_contract_specs_contract_symbol'), table_name='contract_specs')
    op.drop_table('contract_specs')
    op.drop_index('ux_bars_instrument_contract_open', table_name='bars')
    op.drop_index(op.f('ix_bars_instrument'), table_name='bars')
    op.drop_index(op.f('ix_bars_contract_symbol'), table_name='bars')
    op.drop_table('bars')
    # ### end Alembic commands ###
