// server/tierTraits.js
//
// The two tier-level trait sheets the package defines and the engine
// never built.
//
// `VACANCY_TRAIT_DATABASE_ATTACHMENT.md` lists FIVE tier-level sheets
// under "Tier-level trait sheets" and "Culture DNA — tier-level":
// FAMILY, ORGANIZATION, CITY, CIVILIZATION and CULTURE. Four have a
// module — `familyTraits.js`, `organizationTraits.js`, `traits.js` for
// the individual tier, `culture.js` for Culture DNA. CITY and
// CIVILIZATION had none, and `grep -rn "CITY_TRAIT\|CIVILIZATION_TRAIT
// \|tourism" server/*.js` returned nothing at all. Thirty-three named
// dimensions across the two, generated by nothing, read by nothing.
//
// That is where §7's three remaining `absent` urban systems live:
// **20. Government Services**, **35. Military / National Guard** and
// **36. Tourism**. None of the three needed inventing — `tourism` is a
// CITY dimension, `military`, `healthcare`, `education` and `security`
// are CIVILIZATION dimensions, and §49 CITY DNA names "tourism city"
// and "military city" among the nine identities a city can have.
//
// ---------------------------------------------------------------------
// How a dimension earns a row here
//
// `traitDefinitions.js`'s header states the rule, and step 5's
// correction is where it was learned: **a dimension only becomes stored
// trait data if the schema has no dedicated column for it already;
// otherwise it is a direct field, or a computed rollup, and storing it
// a second time produces two disagreeing answers to the same
// question.** Standing rule 3 says the same thing from the other side.
//
// So both sheets below are the SURVIVORS of a reconciliation, not the
// source list. The reconciliation itself is the point of this file and
// is written out in full, because "we checked and this one is already
// answered elsewhere" is exactly the knowledge that evaporates.
//
// ---------------------------------------------------------------------
// CITY — 12 named, 1 stored
//
//   population      cities.population — a headcount, not a 0..100
//                   score. Refreshed from residents.
//   economy         cities.economy — real column. Dead until now; see
//                   territory.refreshCityConditions.
//   safety          cities.safety — real column, same.
//   culture         Culture DNA attaches at the city tier already
//                   (culture.js CULTURE_TIERS includes 'city'). A
//                   second city-culture score would contradict it.
//   infrastructure  cities.infrastructure — real column whose own
//                   schema comment reads "computed rollup from the
//                   infrastructure table below". infrastructure.
//                   cityCondition() is that rollup.
//   education       computed from communities.education, which is
//                   itself a view of resident attainment.
//   technology      the technology ladder is civilization-tier
//                   (technology_eras, civilization_technology_progress)
//                   and cities.reemergence_index is the per-city
//                   reading of how far back up it has climbed. A third
//                   city technology score would be a guess sitting
//                   next to two measurements.
//   resources       `resources` rows are keyed by city_id. Computable.
//   transportation  **deferred.** CLAUDE.md: "Explicitly deferred — do
//                   not touch: ... Transportation". §7 system 7 says
//                   the same. Not a gap; a decision.
//   tourism         **nothing anywhere.** Stored.
//   growth          cities.growth — real column, dead until now.
//   stability       §48 NEIGHBORHOOD STABILITY gives the bands and
//                   says "Stability is dynamically calculated" in the
//                   same breath. Computed — statecraft.stabilityOf —
//                   never stored.
//
// ---------------------------------------------------------------------
// CIVILIZATION — 21 named, 4 stored
//
//   population          sum of city populations.
//   leadership          governments + politics.js. The government is
//                       an organization (standing rule 4) and carries
//                       the organization tier's `leadershipQuality`.
//   economy             mean of city economy.
//   technology          civilizations.era + the era ladder.
//   military            **nothing anywhere.** Stored.
//   education           **stored**, and it is NOT the same number as
//                       CITY education. City education is ATTAINMENT,
//                       a view of who finished what. This is
//                       PROVISION: what the state spends on schools.
//                       Provision drives attainment over time, which
//                       is a mechanism, not a duplicate.
//   healthcare          **stored**, same argument against health.js's
//                       measured outcomes: hospitals funded vs people
//                       well.
//   infrastructure      mean of city infrastructure.
//   transportation      deferred, as above.
//   resources           computable from `resources`.
//   culture             Culture DNA attaches at the civilization tier.
//   religion            npcs.religion — a composition, not a score.
//   innovation          the era ladder again: an unlock IS the
//                       innovation. canUnlock/unlockEra.
//   security            **stored.** Provision again: what the state
//                       spends on public_safety. authority.reachTerm
//                       measures what that buys.
//   justice             justice.js — conviction rate, unlegislated
//                       share, and politics.runLegislation. Measured.
//   trade               market_listings and economy.js.
//   diplomacy           needs a second civilization to be about
//                       anything, and a world has one. A score with no
//                       counterparty is standing rule 11 with extra
//                       steps.
//   environment         environment_state per city.
//   historicalReputation historical_records.
//   citizenHappiness    behavior.moodFor over the population.
//   identity            §49 CITY DNA is the identity mechanic and it
//                       is per-city. A civilization's identity is its
//                       name and era, both real columns.
//
// ---------------------------------------------------------------------
// Where the values live
//
// Not `entity_traits`. Cities and civilizations draw their ids from
// their own counters (`nextCityId`, `nextCivilizationId`), not from
// `nextEntityId`, so they have no `entities` row and an entity_traits
// row for them would violate that table's own foreign key — which is
// precisely the defect the restore pass found in `properties` and
// `cultures`. `culture.js` hit this first and settled it: a tier-level
// entity that is not in the entity id space carries a plain `traits`
// object on its own row, clamped 0..100, defaulting to the schema's
// own `default_value` of 50. Both sheets follow it.
//
// The columns are added in `schema-extensions.sql` as JSONB, the same
// shape `cultures.traits` uses.

'use strict';

// The full named sets, verbatim from the attachment. Kept because the
// reconciliation above is only checkable against them, and because a
// future column for one of these dimensions has to be able to find the
// reason it is not stored here.
const CITY_TRAIT_NAMES = [
  'population', 'economy', 'safety', 'culture', 'infrastructure', 'education',
  'technology', 'resources', 'transportation', 'tourism', 'growth', 'stability',
];

const CIVILIZATION_TRAIT_NAMES = [
  'population', 'leadership', 'economy', 'technology', 'military', 'education',
  'healthcare', 'infrastructure', 'transportation', 'resources', 'culture',
  'religion', 'innovation', 'security', 'justice', 'trade', 'diplomacy',
  'environment', 'historicalReputation', 'citizenHappiness', 'identity',
];

// The survivors — what is actually stored on the row.
const CITY_TRAIT_FAMILIES = ['tourism'];

const CIVILIZATION_TRAIT_FAMILIES = ['military', 'healthcare', 'education', 'security'];

// The four civilization dimensions above are the state's SPENDING
// PRIORITIES and they compete: `statecraft.js` normalises them against
// their own total, so raising the army lowers the schools without any
// separate rule saying so. Named here rather than there because the
// competition is a property of the sheet, not of the delivery pass.
const SERVICE_FAMILIES = ['healthcare', 'education', 'security'];
const FORCE_FAMILY = 'military';

// The schema's own trait `default_value`, not a number chosen here —
// same source `culture.js` and `traitDefinitions.js` use.
const DEFAULT_VALUE = 50;

const clamp = (n, lo = 0, hi = 100) => Math.max(lo, Math.min(hi, n));

function sheetFor(names, given = {}) {
  const traits = {};
  for (const name of names) {
    const value = given?.[name];
    traits[name] = value == null ? DEFAULT_VALUE : clamp(Number(value));
  }
  return traits;
}

// Build a city's stored sheet. Unknown keys are refused rather than
// dropped: a caller passing `technology` has read the attachment and
// not this file, and silently ignoring it would let them believe a
// number was stored.
function cityTraits(given = {}) {
  assertKnown(given, CITY_TRAIT_FAMILIES, CITY_TRAIT_NAMES, 'city');
  return sheetFor(CITY_TRAIT_FAMILIES, given);
}

function civilizationTraits(given = {}) {
  assertKnown(given, CIVILIZATION_TRAIT_FAMILIES, CIVILIZATION_TRAIT_NAMES, 'civilization');
  return sheetFor(CIVILIZATION_TRAIT_FAMILIES, given);
}

function assertKnown(given, stored, named, tier) {
  for (const key of Object.keys(given || {})) {
    if (stored.includes(key)) continue;
    if (named.includes(key)) {
      throw new Error(
        `tierTraits: "${key}" is a ${tier} dimension but is not stored — it is already `
        + 'answered by a column, a rollup or another system. See the reconciliation in '
        + 'server/tierTraits.js.',
      );
    }
    throw new Error(
      `tierTraits: "${key}" is not a ${tier} trait. The ${named.length} are: ${named.join(', ')}.`,
    );
  }
}

// Read one dimension off a row, whatever state that row is in. A city
// generated before this file existed, or restored from a database that
// predates the column, has no sheet at all — and that is an unknown
// rather than a zero.
function traitOf(row, name) {
  const value = row?.traits?.[name];
  if (value === null || value === undefined) return null;
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

module.exports = {
  CITY_TRAIT_NAMES,
  CIVILIZATION_TRAIT_NAMES,
  CITY_TRAIT_FAMILIES,
  CIVILIZATION_TRAIT_FAMILIES,
  SERVICE_FAMILIES,
  FORCE_FAMILY,
  DEFAULT_VALUE,
  cityTraits,
  civilizationTraits,
  traitOf,
};
